export const paymentsData = [
  {
    id: 1,
    type: "Project",
    business: "GreenMart",
    expert: "Ummni Abdullah",
    amount: "₦145,000",
    trxId: "8772HG",
    status: "Paid",
    date: "Dec 4, 2019",
    avatar: "/images/profile-pics.svg",
  },
  {
    id: 2,
    type: "Consultation",
    business: "Bella+",
    expert: "David Eze",
    amount: "₦12,000",
    trxId: "8772HG",
    status: "Pending",
    date: "Jul 4, 2019",
    avatar: "/images/profile-pics.svg",
  },
  {
    id: 3,
    type: "Project",
    business: "SubletAI+",
    expert: "Kasan Driah",
    amount: "₦12,000",
    trxId: "8772HG",
    status: "Funded (not released)",
    date: "Jul 4, 2019",
    avatar: "/images/profile-pics.svg",
  },
  {
    id: 4,
    type: "Subscription",
    business: "LandHub",
    expert: "Amina Lawal",
    amount: "₦25,000",
    trxId: "9821KL",
    status: "Paid",
    date: "Jan 15, 2020",
    expertAvatar: "/images/profile-pics.svg",
  },
  {
    id: 5,
    type: "Consultation",
    business: "TechFarm",
    expert: "John Okafor",
    amount: "₦18,500",
    trxId: "7563MN",
    status: "Pending",
    date: "Mar 22, 2020",
    expertAvatar: "/images/profile-pics.svg",
  },
  {
    id: 6,
    type: "Project",
    business: "FoodExpress",
    expert: "Sarah Johnson",
    amount: "₦85,000",
    trxId: "1234AB",
    status: "Paid",
    date: "Apr 10, 2020",
    expertAvatar: "/images/profile-pics.svg",
  },
  {
    id: 7,
    type: "Consultation",
    business: "HealthPlus",
    expert: "Michael Brown",
    amount: "₦15,000",
    trxId: "5678CD",
    status: "Pending",
    date: "May 5, 2020",
    expertAvatar: "/images/profile-pics.svg",
  },
  {
    id: 8,
    type: "Subscription",
    business: "EduTech",
    expert: "Emily Davis",
    amount: "₦30,000",
    trxId: "9012EF",
    status: "Paid",
    date: "Jun 18, 2020",
  },
  {
    id: 9,
    type: "Project",
    business: "AutoCare",
    expert: "Robert Wilson",
    amount: "₦120,000",
    trxId: "3456GH",
    status: "Funded (not released)",
    date: "Jul 22, 2020",
  },
  {
    id: 10,
    type: "Consultation",
    business: "FashionHub",
    expert: "Lisa Moore",
    amount: "₦22,000",
    trxId: "7890IJ",
    status: "Pending",
    date: "Aug 7, 2020",
  },
];

// Dummy data for Subscriptions tab
export const subscriptionsData = [
  {
    id: 1,
    business: "GreenMart",
    plan: "Padi Pro",
    amount: "₦145,000",
    renewal: "Dec 4, 2019",
    status: "Active",
    avatar: "/images/profile-pics.svg",
  },
  {
    id: 2,
    business: "Bella+ Nigeria ltd.",
    plan: "Padi Yakata",
    amount: "₦12,000",
    renewal: "Jul 4, 2019",
    status: "Expired",
    avatar: "/images/profile-pics.svg",
  },
  {
    id: 3,
    business: "LandHub",
    plan: "Starter Free",
    amount: "₦0",
    renewal: "Jul 4, 2019",
    status: "Trial",
    avatar: "/images/profile-pics.svg",
  },
  {
    id: 4,
    business: "SubletAI+",
    plan: "Padi Pro",
    amount: "₦145,000",
    renewal: "Aug 10, 2020",
    status: "Active",
  },
  {
    id: 5,
    business: "TechFarm Solutions",
    plan: "Padi Basic",
    amount: "₦45,000",
    renewal: "Sep 5, 2020",
    status: "Active",
  },
  {
    id: 6,
    business: "FoodExpress",
    plan: "Padi Pro",
    amount: "₦145,000",
    renewal: "Oct 15, 2020",
    status: "Active",
  },
  {
    id: 7,
    business: "HealthPlus",
    plan: "Padi Basic",
    amount: "₦45,000",
    renewal: "Nov 2, 2020",
    status: "Expired",
  },
  {
    id: 8,
    business: "EduTech",
    plan: "Padi Yakata",
    amount: "₦12,000",
    renewal: "Dec 10, 2020",
    status: "Active",
  },
  {
    id: 9,
    business: "AutoCare",
    plan: "Starter Free",
    amount: "₦0",
    renewal: "Jan 5, 2021",
    status: "Trial",
  },
  {
    id: 10,
    business: "FashionHub",
    plan: "Padi Pro",
    amount: "₦145,000",
    renewal: "Feb 18, 2021",
    status: "Active",
  },
];

// Dummy data for Expert Payout tab
export const expertPayoutData = [
  {
    id: 1,
    expert: "Ummni Abdullah",
    amount: "₦145,000",
    trxId: "PAY-8772HG",
    status: "Paid",
    date: "Dec 4, 2019",
    method: "Bank Transfer",
    type: "Project",
    avatar: "/images/profile-pics.svg",
  },
  {
    id: 2,
    expert: "David Eze",
    amount: "₦12,000",
    trxId: "PAY-7563MN",
    status: "Pending",
    date: "Jul 4, 2019",
    method: "PayPal",
    type: "Consultation",
    avatar: "/images/profile-pics.svg",
  },
  {
    id: 3,
    expert: "Kasan Driah",
    amount: "₦12,000",
    trxId: "PAY-9821KL",
    status: "Processing",
    date: "Jul 4, 2019",
    method: "Bank Transfer",
    type: "Subscription",
  },
  {
    id: 4,
    expert: "Amina Lawal",
    amount: "₦25,000",
    trxId: "PAY-3456PQ",
    status: "Paid",
    date: "Jan 15, 2020",
    method: "PayPal",
    type: "Email Fix",
    expertAvatar: "/images/profile-pics.svg",
  },
  {
    id: 5,
    expert: "John Okafor",
    amount: "₦18,500",
    trxId: "PAY-7890RS",
    status: "Failed",
    date: "Mar 22, 2020",
    method: "Bank Transfer",
    type: "Funnel Setup",
    expertAvatar: "/images/profile-pics.svg",
  },
  {
    id: 6,
    expert: "Sarah Johnson",
    amount: "₦85,000",
    trxId: "PAY-1234AB",
    status: "Paid",
    date: "Apr 10, 2020",
    method: "PayPal",
    type: "Project",
    expertAvatar: "/images/profile-pics.svg",
  },
  {
    id: 7,
    expert: "Michael Brown",
    amount: "₦15,000",
    trxId: "PAY-5678CD",
    status: "Processing",
    date: "May 5, 2020",
    method: "Bank Transfer",
    type: "Consultation",
  },
  {
    id: 8,
    expert: "Emily Davis",
    amount: "₦30,000",
    trxId: "PAY-9012EF",
    status: "Paid",
    date: "Jun 18, 2020",
    method: "PayPal",
    type: "Subscription",
  },
  {
    id: 9,
    expert: "Robert Wilson",
    amount: "₦120,000",
    trxId: "PAY-3456GH",
    status: "Pending",
    date: "Jul 22, 2020",
    method: "Bank Transfer",
    type: "Project",
  },
  {
    id: 10,
    expert: "Lisa Moore",
    amount: "₦22,000",
    trxId: "PAY-7890IJ",
    status: "Failed",
    date: "Aug 7, 2020",
    method: "PayPal",
    type: "Consultation",
  },
];

export const statusStyles = {
  Paid: "bg-green-100/50 text-green-500/70 border border-green-500/70",
  Pending: "bg-yellow-100/50 text-yellow-500/70 border border-yellow-500/70",
  Processing: "bg-blue-100/50 text-blue-500/70 border border-blue-500/70",
  Failed: "bg-red-100/50 text-red-500/70 border border-red-500/70",
  "Funded (not released)":
    "bg-purple-100/50 text-purple-500/70 border border-purple-500/70",
  Active: "bg-green-100/50 text-green-500/70 border border-green-500/70",
  Expired: "bg-yellow-100/50 text-yellow-500/70 border border-yellow-500/70",
  Trial: "bg-gray-100/50 text-gray-500/70 border border-gray-500/70",
};

export const tabs = [
  { label: "Payments", value: "payments" },
  { label: "Subscriptions", value: "subscriptions" },
  { label: "Expert Payout", value: "expertPayout" },
];

export const paymentTypes = [
  "All payments",
  "Paid",
  "Pending",
  "Funded (not released)",
];

export const payoutStatuses = [
  "All statuses",
  "Paid",
  "Pending",
  "Processing",
  "Failed",
];

// Dummy data for Admin Users
export const AdminUserList = [
  {
    id: 1,
    name: "Titi Ayomide",
    email: "titi@scalepadi.com",
    role: "Super Admin",
    lastActive: "2 hrs ago",
    status: "Active",
    phoneNumber: "23412345678",
  },
  {
    id: 2,
    name: "John Doe",
    email: "john@scalepadi.com",
    role: "Admin",
    lastActive: "1 day ago",
    status: "Active",
    phoneNumber: "23412345678",
  },
  {
    id: 3,
    name: "Jane Smith",
    email: "jane@scalepadi.com",
    role: "Support",
    lastActive: "3 days ago",
    status: "Inactive",
    phoneNumber: "23412345678",
  },
  {
    id: 4,
    name: "Mike Johnson",
    email: "mike@scalepadi.com",
    role: "Viewer",
    lastActive: "1 week ago",
    status: "Active",
    phoneNumber: "23412345678",
  },
  {
    id: 5,
    name: "Sarah Williams",
    email: "sarah@scalepadi.com",
    role: "Admin",
    lastActive: "5 hours ago",
    status: "Active",
    phoneNumber: "23412345678",
  },
  {
    id: 6,
    name: "David Brown",
    email: "david@scalepadi.com",
    role: "Support",
    lastActive: "2 days ago",
    status: "Active",
    phoneNumber: "23412345678",
  },
  {
    id: 7,
    name: "Emily Davis",
    email: "emily@scalepadi.com",
    role: "Viewer",
    lastActive: "1 month ago",
    status: "Inactive",
    phoneNumber: "23412345678",
  },
  {
    id: 8,
    name: "Robert Wilson",
    email: "robert@scalepadi.com",
    role: "Admin",
    lastActive: "1 week ago",
    status: "Active",
    phoneNumber: "23412345678",
  },
  {
    id: 9,
    name: "Lisa Moore",
    email: "lisa@scalepadi.com",
    role: "Super Admin",
    lastActive: "3 days ago",
    status: "Active",
    phoneNumber: "23412345678",
  },
  {
    id: 10,
    name: "Thomas Taylor",
    email: "thomas@scalepadi.com",
    role: "Support",
    lastActive: "Just now",
    status: "Active",
    phoneNumber: "23412345678",
  },
];